# Generated by Django 5.1.15 on 2026-06-14 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_courier_id_alter_historicalorder_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="courier",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="courier",
            name="phone",
            field=models.CharField(
                db_index=True, max_length=20, verbose_name="Телефон"
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="id",
            field=models.IntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="id",
            field=models.IntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="name",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrestaurant",
            name="id",
            field=models.IntegerField(
                auto_created=True, blank=True, db_index=True, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrestaurant",
            name="name",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="Название"
            ),
        ),
        migrations.AddIndex(
            model_name="courier",
            index=models.Index(fields=["is_active"], name="courier_active_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="order_status_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "created_at"], name="order_customer_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["restaurant", "status"], name="order_restaurant_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["restaurant", "name"], name="product_restaurant_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="product_price_idx"),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(fields=["name"], name="restaurant_name_idx"),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(
                fields=["owner", "created_at"], name="restaurant_owner_created_idx"
            ),
        ),
    ]
